### ISSUE TITLE
Does not compile under rust 1.0.0-beta3

### ISSUE THREAD

**Issue by negge** [thehydroimpulse/postgres-extension.rs#5]
I just installed rust and could not get this project to build:

$ rustc --version
rustc 1.0.0-beta.3 (5241bf9c3 2015-04-25) (built 2015-04-25)

$ cargo build --verbose
   Compiling postgres_extension v0.0.1 (file:///home/nathan/git/postgres-extension.rs)
     Running `rustc src/lib.rs --crate-name postgres_extension --crate-type dylib -g -C metadata=ccbbb938512147eb -C extra-filename=-ccbbb938512147eb --out-dir /home/nathan/git/postgres-extension.rs/target/debug --emit=dep-info,link -L dependency=/home/nathan/git/postgres-extension.rs/target/debug -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps`
src/lib.rs:7:20: 7:37 error: unresolved import `core::marker::InvariantLifetime`. There is no `InvariantLifetime` in `core::marker`
src/lib.rs:7 use core::marker::{InvariantLifetime, MarkerTrait};
                                ^~~~~~~~~~~~~~~~~
src/lib.rs:7:39: 7:50 error: unresolved import `core::marker::MarkerTrait`. There is no `MarkerTrait` in `core::marker`
src/lib.rs:7 use core::marker::{InvariantLifetime, MarkerTrait};
                                                   ^~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `postgres_extension`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name postgres_extension --crate-type dylib -g -C metadata=ccbbb938512147eb -C extra-filename=-ccbbb938512147eb --out-dir /home/nathan/git/postgres-extension.rs/target/debug --emit=dep-info,link -L dependency=/home/nathan/git/postgres-extension.rs/target/debug -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps` (exit code: 101)

**Comment by thehydroimpulse** [comment]
Yeah, this project hasn't been updated to match the current Rust version in a while. It was more of an experimentation than anything else.

**Comment by negge** [comment]
This is still not compiling for me after the latest pull request.  The error is different though:

$ rustc --version
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

$ cargo build --verbose
   Compiling libc v0.1.8
     Running `rustc /home/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.8/rust/src/liblibc/lib.rs --crate-name libc --crate-type lib -g --cfg feature="cargo-build" --cfg feature="default" -C metadata=2eda841eb12a3090 -C extra-filename=-2eda841eb12a3090 --out-dir /home/nathan/git/postgres-extension.rs/target/debug/deps --emit=dep-info,link -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps -Awarnings`
   Compiling postgres_extension v0.0.1 (file:///home/nathan/git/postgres-extension.rs)
     Running `rustc src/lib.rs --crate-name postgres_extension --crate-type dylib -g -C metadata=ccbbb938512147eb -C extra-filename=-ccbbb938512147eb --out-dir /home/nathan/git/postgres-extension.rs/target/debug --emit=dep-info,link -L dependency=/home/nathan/git/postgres-extension.rs/target/debug -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps --extern libc=/home/nathan/git/postgres-extension.rs/target/debug/deps/liblibc-2eda841eb12a3090.rlib`
src/lib.rs:13:1: 13:30 warning: type `fmNodePtr` should have a camel case name such as `Fmnodeptr`, #[warn(non_camel_case_types)] on by default
src/lib.rs:13 type fmNodePtr = *mut c_void;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:14:1: 14:32 warning: type `fmAggrefPtr` should have a camel case name such as `Fmaggrefptr`, #[warn(non_camel_case_types)] on by default
src/lib.rs:14 type fmAggrefPtr = *mut c_void;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:463:5: 463:35 warning: struct field is never used: `ptr`, #[warn(dead_code)] on by default
src/lib.rs:463     ptr: *mut FunctionCallInfoData,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:471:5: 471:15 warning: struct field is never used: `val`, #[warn(dead_code)] on by default
src/lib.rs:471     val: usize
                   ^~~~~~~~~~
src/lib.rs:475:20: 475:25 warning: unused variable: `value`, #[warn(unused_variables)] on by default
src/lib.rs:475     pub fn new_str(value: &str) -> Datum {
                                  ^~~~~
src/lib.rs:1:1: 1:18 error: unstable feature
src/lib.rs:1 #![feature(core)]
             ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error
Could not compile `postgres_extension`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name postgres_extension --crate-type dylib -g -C metadata=ccbbb938512147eb -C extra-filename=-ccbbb938512147eb --out-dir /home/nathan/git/postgres-extension.rs/target/debug --emit=dep-info,link -L dependency=/home/nathan/git/postgres-extension.rs/target/debug -L dependency=/home/nathan/git/postgres-extension.rs/target/debug/deps --extern libc=/home/nathan/git/postgres-extension.rs/target/debug/deps/liblibc-2eda841eb12a3090.rlib` (exit code: 101)
